### ISSUE TITLE
DFD Comments Feb 1

### ISSUE THREAD

**Issue by germonprez** [gcrowl/ISQA3420001.1171-2017-Spring--ISQA-3420-001-MANAGING-IN-A-DIGITAL-WORLD#9]
Here are a few (one) comment: 

1) You can remove the procurement process. Simply have the developer send directly to Scan for OSS Components. 

MG

**Comment by gcrowl** [comment]
![software scan 1](https://cloud.githubusercontent.com/assets/25048836/22742586/df2c9d8a-eddc-11e6-8eb6-2b7cf10abe58.png)

**Comment by gcrowl** [comment]
Updated Image per suggestion
